default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_PGSQL_USERNAME") { "" } %>
  password: <%= ENV.fetch("DB_PGSQL_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_PGSQL_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PGSQL_PORT") { 5432 } %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: commerceos_development
  
test:
  <<: *default
  database: commerceos_test

production:
  primary: &primary_production
    <<: *default
    database: commerceos
    username: <%= ENV.fetch("DB_PGSQL_USERNAME") { "" } %>
    password: <%= ENV.fetch("DB_PGSQL_PASSWORD") { "" } %>
  cache:
    <<: *primary_production
    database: commerceos_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: commerceos_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: commerceos_cable
    migrations_paths: db/cable_migrate
