# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_good_job_finished_jobs:
    command: "GoodJob::Job.where.not(finished_at: nil).where('finished_at < ?', 7.days.ago).delete_all"
    schedule: every hour at minute 12
