source "https://rubygems.org"

gem "rails", "~> 8.1.3"

gem "pg"

gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "kamal", require: false

gem "thruster", require: false

gem "image_processing"

gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "pundit"
gem "blueprinter"
gem "pagy"
gem "money-rails"
gem "audited"
gem "discard"
gem "aws-sdk-s3", require: false
gem "roo"
gem "dotenv-rails"
gem "rswag"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "bullet"
end
